# ThoTH @ 26-Nov-2018
status = warn
name= properties_configuration

# Give directory path where log files should get stored
#local
property.basePath = c:\\sdilog\\eminds\\
#TNT
#property.basePath = /home/eminds/tomcat/logs/
#LIVE
#property.basePath = /home/emindstrial/tomcat/logs/
#property.basePath = /var/log/sdilog/impian2/
#property.basePath = /home/emindstrial/tomcat/logs/
#property.basePath = /root/software/sdilog/

# ConsoleAppender will print logs on console
appender.console.type = Console
appender.console.name = consoleLogger
appender.console.target = SYSTEM_OUT
appender.console.layout.type = PatternLayout
# Specify the pattern of the logs
#appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] [%c] [%M] [%l] - %msg%n
appender.console.layout.pattern = %d{HH:mm:ss.SSS} %highlight{%d [%t] %-5level: %msg%n%throwable}
# to use the highlighter
appender.console.layout.disableAnsi = false


# RollingFileAppender will print logs in file which can be rotated based on time or size
appender.rolling.type = RollingFile
appender.rolling.name = fileLogger
appender.rolling.fileName= ${basePath}app.log
appender.rolling.filePattern= ${basePath}app_%i.log
#appender.rolling.filePattern= ${basePath}app_%d{yyyyMMdd}.log.gz
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %level [%t] [%c] [%M] [%l] - %msg%n
appender.rolling.policies.type = Policies

# Rotate log file each day and keep 30 days worth
#appender.rolling.policies.time.type = TimeBasedTriggeringPolicy
#appender.rolling.policies.time.interval = 1
#appender.rolling.policies.time.modulate = true
#appender.rolling.strategy.type = DefaultRolloverStrategy
#appender.rolling.strategy.delete.type = Delete
#appender.rolling.strategy.delete.basePath = ${basePath}
#appender.rolling.strategy.delete.maxDepth = 1
#appender.rolling.strategy.delete.ifLastModified.type = IfLastModified
## Delete files older than 30 days
#appender.rolling.strategy.delete.ifLastModified.age = 30d

appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size=2MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 30

# Mention package name here in place of example. Classes in this package or subpackages will use ConsoleAppender and RollingFileAppender for logging         
logger.sains.name = com.sains
logger.sains.level = debug
logger.sains.additivity = false
logger.sains.appenderRef.rolling.ref = fileLogger
logger.sains.appenderRef.console.ref = consoleLogger

# Mention package name here in place of example. Classes in this package or subpackages will use ConsoleAppender and RollingFileAppender for logging         
logger.sains.name = com.sample
logger.sains.level = debug
logger.sains.additivity = false
logger.sains.appenderRef.rolling.ref = fileLogger
logger.sains.appenderRef.console.ref = consoleLogger

logger.hb.name = com.mchange
logger.hb.level = INFO
logger.hb.additivity = false
logger.hb.appenderRef.rolling.ref = fileLogger
logger.hb.appenderRef.console.ref = consoleLogger
#
#logger.webservice.name = com.webservice
#logger.webservice.level = debug
#logger.webservice.additivity = false
#logger.webservice.appenderRef.rolling.ref = fileLogger
#logger.webservice.appenderRef.console.ref = consoleLogger

# Configure root logger for logging error logs in classes which are in package other than above specified package
# ThoTH Level: Trace > Debug > Info > Warn > Error > Fatal
rootLogger.level = debug
#rootLogger.additivity = false
#rootLogger.appenderRef.rolling.ref = fileLogger
#rootLogger.appenderRef.console.ref = consoleLogger