#common
comm.butiran=Butiran
comm.tajuk=Tajuk
comm.gred=Gred
comm.bilangan=Bilangan
comm.bil=Bil.
comm.jawatan=Jawatan
comm.kenyataan=Kenyataan
comm.kepala=Kepala
comm.idJawatan=ID Jawatan
comm.tarafJawatan=Taraf Jawatan
comm.none=Tiada
comm.jumlah=Jumlah
comm.jumlahBesar=Jumlah Besar

#Angaran Belanjawan Rpt
angaranBelanja.title=Anggaran Belanjawan Negeri Sarawak
angaranBelanja.pegawaiPengawal=Pegawai Pengawal
angaranBelanja.taraf.tetap=TETAP
angaranBelanja.taraf.jbc=JBC
angaranBelanja.taraf.tambahsentara=TAMBAHSENTARA
