##//- connection info --//
#TNT
hbUrl=jdbc:oracle:thin:@172.26.80.144:1521/MUDB
hbUser=mudb
hbPass=1ass1cdw190j18m9

#Live
#hbUrl=jdbc:oracle:thin:@172.29.26.11:1521/MUDB
#hbUser=mudb_user
#hbPass=1ass1cdw190j18m91cdw1bzm197o1bsh

TraceOperation.fileLocation=C:\sdslog\forNewProject\ModelOperation\

#TraceOperation.fileLocation=sdslog\forNewProject\ModelOperation\

#fileOperation :: obs or ftps or sftp
fileOperation=obs
#obs.endPoint=https://obs.dsancloud.com
#obs.ak=99SBRW8NB8EXVW1VQLRO
#obs.sk=CNcFuvlQ2UwWdvGd94vS6a2O6A0QjdngxNO8GznQ

# 12/08/2024 updated obs endpoint and credentials
obs.endPoint=obsv3.swk-kch-1.hcs.dsancloud.com
obs.ak=MTDK3SQPTRMXENXVCWLZ
obs.sk=OtfFkc7bvYRtT22IId4S851WI05kWc4yDv7Mf4Qc
obs.bucketName=tnt-share
pathPrefix=obs-utimaps-tnt/pb/

#obs.endPoint=https://obs.dsancloud.com
#obs.ak=Z1X4YZLNUEOBNCHNJOVI
#obs.sk=aEh12b2b01V1DSCi6VA5X42LxvfWglKzZyhFX4rn
#obs.bucketName=obs-test-20200805

fs.url=172.26.80.96
fs.user=sftp-lasisdemo
fs.pass=1pjl1pda1pqq1os31xfj1op71ppo1pao1pil
fs.port=8022
fs.pathPrefix=/home/elasis/attachment/eLasis/download/utimaps/usp/

#pathPrefix=/home/ela2bcsc/uploads/
#fs.url=172.26.85.24
#fs.user=ela2bcsc
#fs.pass=ela2bcsc@SDS
#fs.port=8022

#pathPrefix=/home/ela2bcs/public_html/FlexPaper_Annotations_Trial/pdf/
#fs.url=172.26.85.34
#fs.user=ela2bcs
#fs.pass=ela2bcs@SDS
#fs.port=22


#//-SMS --//
sms.url=http://smstplive.sains.com.my/?<api_key>&to=<sms_phoneNo>&message=<sms_msg>

##-- Email & SMS queue processing size --##
queue.sms.processSize=20
queue.email.processSize=20

#//-SMTP --//
smtp.default=smtp.sarawaknet.gov.my


#//-log file path --//
logPath=c:\\sdilog\\eSPA\\

#//-domain param --//
server_url=http://localhost:8080/forNewProject
portal_url=http://localhost:8080/forNewProject
feedbackEmail=support@system.gov.my
nameForEmail=system.nameForEmail

#//-SarawakID --//
swkid.enabled=n
swkid.SYSTEM_URL=http://localhost:8080/aquila
swkid.CLIENT_ID=FDS
swkid.SECRET=26c135fa428cc2a58209d0692cbb0b95
swkid.PLUGIN_URL=https://sarawakid-tnt.sarawak.gov.my/web/share/swkid_plugin/?lang=en
swkid.VALIDATE_LOGIN_URL=https://sarawakid-tnt.sarawak.gov.my/web/apiv1/login
swkid.API_URL=https://sarawakid-tnt.sarawak.gov.my/web/apiv1/
swkid.profile_get=https://sarawakid-tnt.sarawak.gov.my/web/apiv1/profile_get/
swkid.API_TOKEN_EXCHANGE=token_exchange
swkid.API_TOKEN_USER=token_user
swkid.API_USER_GET=user_get
swkid.API_LOGIN=login

#//-- FIM --//
fim.enabled=y
fim.AUTHORIZE_URL=https://fim2.lab.sains.com.my/oauth/v1/authorize
fim.CLIENT_ID=test-TOwAo45r52fO3A9gD4IbMrmkbAkIr4RU-apps.sains.com.my
fim.SECRET=CRrxSFPRzLSywvcxrFlSYKqcJdEvbbbLDAiuohEesONjjUNnOgNVclXFzqEknYSg
fim.TOKEN_URL=https://fim2.lab.sains.com.my/oauth/v1/token
fim.USERINFO_URL=https://fim2.lab.sains.com.my/oauth/v1/userinfo
fim.REDIRECT_URL=http://thensw.sains.com.my:8080/forNewProject/fim2VerifyLogin
fim.SCOPE=openid

#//-Route Workflow --//
#route.url=http://localhost:8080/workflow_ora/WfService_
#route.url=https://172.26.80.96:8010/route_ora/WfService_
route.url=https://route.tnt.sarawak.gov.my/route_ora/WfService_
#route.url=https://lxg-wf.sains.com.my/route_ora/WfService_

#//-Schedular --//
jobStarter.startValue=60

#//-System Info --//
war_version=2020.10.01.01 (any other info)

#//- Static Variable File Path --//
staticVarFilePath=C:\\sdslog\\staticVar.properties

accessControlAllowOrigin=https://sarawakid-tnt.sarawak.gov.my,https://sarawakid.sarawak.gov.my,https://escholarship.tnt.sarawak.gov.my,https://fim2.lab.sains.com.my
defaultAccessControlAllowOrigin=https://utilitysurvey-tnt.sarawak.gov.my

#//- Timeout Countdown --//
countdown.enable=false
countdown.warningSecond=20
countdown.stayAfterTimeout=true/false

#defaultApiServer=http://thensw.sains.com.my:8080/forNewProject_ApiCall
defaultApiServer=http://thensw.sains.com.my:8080/forNewProject
#apiMethodServer=apiCall_1Sample::http://thensw.sains.com.my:8080/forNewProject_ApiCall;apiCall_2Sample::http://localhost:8080/forNewProject_ApiCall
apiMethodServer=apiCall_1SampleApi::http://thensw.sains.com.my:8080/forNewProject;apiCall_2Sample::http://localhost:8080/forNewProject
#apiMethodSetup=apiCall_1Sample::UppyParentModel.ChildList.DrDocRepoModel,ChildList.DrDocRepoModel2;apiCall_2Sample::UppyModel.DrDocRepoModel;apiCall_3Sample::LIST
apiMethodSetup=apiCall_1SampleApi;apiCall_2Sample;apiCall_3Sample
apiSetup.apiCall_1SampleApi=UppyParentModel.ChildList.DrDocRepoModel,ChildList.DrDocRepoModel2
apiSetup.apiCall_2Sample=UppyModel.DrDocRepoModel
apiSetup.apiCall_3Sample=LIST

#API Consumer : START
ForNewProject.Api.Consumer.key=api_key_1
ForNewProject.Api.Consumer.secret=api_secret_1
ForNewProject.Api.Consumer.tokenUrl=http://localhost:8080/forNewProject/token
ForNewProject.Api.Consumer.refreshUrl=http://localhost:8080/forNewProject/refresh
ForNewProject.Api.Consumer.revokeUrl=http://localhost:8080/forNewProject/revoke

OtherSystem.Api.Consumer.key=api_key_las
OtherSystem.Api.Consumer.secret=L@sS3CR3T
OtherSystem.Api.Consumer.tokenUrl=https://lxg-lasis.tnt.sarawak.gov.my/las/token
OtherSystem.Api.Consumer.refreshUrl=https://lxg-lasis.tnt.sarawak.gov.my/las/refresh
OtherSystem.Api.Consumer.revokeUrl=https://lxg-lasis.tnt.sarawak.gov.my/las/revoke

LXG_MAIN.Api.Consumer.key=api_key_1
LXG_MAIN.Api.Consumer.secret=api_secret_1
LXG_MAIN.Api.Consumer.tokenUrl=https://lxg-lasis.tnt.sarawak.gov.my/common/token
LXG_MAIN.Api.Consumer.refreshUrl=https://lxg-lasis.tnt.sarawak.gov.my/common/refresh
LXG_MAIN.Api.Consumer.revokeUrl=https://lxg-lasis.tnt.sarawak.gov.my/common/revoke

#Live
#LXG_MAIN.Api.Consumer.key=api_key_1
#LXG_MAIN.Api.Consumer.secret=api_secret_1
#LXG_MAIN.Api.Consumer.tokenUrl=https://lxg-lasis.sarawak.gov.my/common/token
#LXG_MAIN.Api.Consumer.refreshUrl=https://lxg-lasis.sarawak.gov.my/common/refresh
#LXG_MAIN.Api.Consumer.revokeUrl=https://lxg-lasis.sarawak.gov.my/common/revoke

## //-- For ISM (TNT). --//
#ism.consumer.key=4_JWfz9ld5eCSO1G67hRWWf29cAa
#ism.consumer.secret=LezeDl26fPaKSW13Liz6ZB48W1ga
ism.consumer.key=FKSS5U4rVRGhWHZLjfToBZotfuga
ism.consumer.secret=24HE7oTjZYGd2T4e0ET5ZLvIVj0a
ism.token.url=https://apitnt.sains.com.my/token
ism.agency.id=24
ism.agency.name=Land and Survey
ism.url.context=https://apitnt.sains.com.my/service_sarawak/v1.0
ism.service.id.usjapp=662
ism.service.id.usjsub=663
#ism.service.id.apply.licence=614
#ism.service.id.apply.permit=615
#ism.service.id.apply.storageopr=616
#ism.service.id.extend.licence=701
#ism.service.id.manage.storage.site=702
#ism.service.id.terminate.storage.operator=700
ism.payment.history.token=f501a2ab5da785d25ae3ca1b6a789a5b