##//- connection info --//
hbUrl=jdbc:mysql://localhost:3306/db20200225?useSSL=false&amp;serverTimezone=Asia/Kuala_Lumpur
hbUser=root
hbPass=pass4local
#//-File Storage (OBS[obs.], FTP[fs.]) --//
pathPrefix=sftp/
obs.endPoint=https://obs.dsancloud.com
obs.ak=TSJXLNOPDCWHTOULQJSG
obs.sk=jErlj9wetFCSDtnj4OY9ougPpXxvZWyujhKmcFXg
obs.bucketName=obs-sftp
fs.url=10.17.100.22
fs.user=espa
fs.pass=password
fs.port=8022

#//-SMS --//
sms.url=http://smstplive.sains.com.my/?<api_key>&to=<sms_phoneNo>&message=<sms_msg>

#//-SMTP --//
smtp.default=smtp.sarawaknet.gov.my

#//-log file path --//
logPath=c:\\sdilog\\eSPA\\

#//-domain param --//
server_url=http://localhost:8084/forNewProject
portal_url=http://localhost:8084/forNewProject
feedbackEmail=support@system.gov.my
nameForEmail=system.nameForEmail
#//-SarawakID --//
swkid.enabled=y
swkid.SYSTEM_URL=http://10.17.101.219:8080/forNewProject
swkid.CLIENT_ID=FDS
swkid.SECRET=26c135fa428cc2a58209d0692cbb0b95
swkid.PLUGIN_URL=https://sarawakid-tnt.sarawak.gov.my/web/share/swkid_plugin/?lang=en
swkid.VALIDATE_LOGIN_URL=https://sarawakid-tnt.sarawak.gov.my/web/apiv1/login
swkid.API_URL=https://sarawakid-tnt.sarawak.gov.my/web/apiv1/
swkid.profile_get=https://sarawakid-tnt.sarawak.gov.my/web/apiv1/profile_get/
swkid.API_TOKEN_EXCHANGE=token_exchange
swkid.API_TOKEN_USER=token_user
swkid.API_USER_GET=user_get
swkid.API_LOGIN=login

#//-Route Workflow --//
route.url=http://localhost:8080/route/WfService_

#//-Schedular --//
jobStarter.startValue=60

#//-System Info --//
war_version=2020.10.01.01 (any other info)

#//- Static Variable File Path --//
staticVarFilePath=C:\\sdslog\\staticVar.properties